---
# tasks file for nginx-dockerhost-init

- name: install docker-latest
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-python
    - docker-latest

- name: start docker-latest
  systemd:
    name: docker-latest
    enabled: yes
    state: started
